In [72]:
Students_name1 =['naina','karuna','shanu','suman']
Students_name1

['naina', 'karuna', 'shanu', 'suman']

In [73]:
students_name[1] ="karu"
students_name

TypeError: 'tuple' object does not support item assignment

In [74]:
students_name1[1] ="karu"
students_name1

NameError: name 'students_name1' is not defined

In [75]:
students_name[1] ="karu"
students_name

TypeError: 'tuple' object does not support item assignment

In [76]:
students_name[1]="karu"
students_name

TypeError: 'tuple' object does not support item assignment

In [77]:
students_name(1)="karu"
students_name

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (992262321.py, line 1)

In [78]:
student_list =[12,4.2,"Hi",1-2j]
student_list

[12, 4.2, 'Hi', (1-2j)]

In [79]:
student_list[2]="Hello"
student_list

[12, 4.2, 'Hello', (1-2j)]

In [82]:
import numpy as np

In [88]:
simple_list=[6,7,9]
np.array(simple_list)

In [90]:
simple_list[2]="Hello"

In [91]:
simple_list

[6, 7, 'Hello']

In [92]:
import array

In [97]:
array.array('i',[6,7])

array('i', [6, 7])

In [98]:
student_list =[12,4.2,"Hi",1-2j]
student_list

[12, 4.2, 'Hi', (1-2j)]

In [99]:
student_list[2]

'Hi'

In [101]:
student_list[3]=23
student_list

[12, 4.2, 'Hi', 23]

In [108]:
student_list[1:4]

[4.2, 'Hi', 23]

In [123]:
list=["x","y","z","s"]

In [110]:
len(list)

3

In [111]:
list[1:3]

['y', 'z']

In [120]:
list[-4:-2]

['x', 'y']

In [128]:
fruit=["Apple,"mango","grapes","guawa"]
fruit.append("mango")


SyntaxError: invalid syntax. Perhaps you forgot a comma? (2363346201.py, line 1)

In [140]:
fruit=["Apple"]
fruit.append("Mango")

In [141]:
import array
import numpy as np

In [296]:
shanu_array12 = array.array('j',[1,12j,30,49,59])
print(shanu_array12)

shan_array_new = shanu_array12[:2] + array.array('j',[12j]) + shanu_array12[2:]
print(shan_array_new)

ValueError: bad typecode (must be b, B, u, h, H, i, I, l, L, q, Q, f or d)

In [166]:
 shan_array_new2 = shan_array_new[:4] + array.array('i',[35]) + shan_array_new[4:len(shan_array_new)]
 print(shan_array_new2)

array('i', [1, 10, 12, 30, 35, 49, 59])


In [181]:
shan_array_new2.append(65)
print(shan_array_new2)



array('i', [65, 65])


In [188]:
shan_array_new2.append(10)
print(shan_array_new2)


array('i', [65, 3, 5, 10])


In [202]:
import numpy as nm

In [211]:
sham_array = array.array('i',[1,10,30,49,59])
print(sham_arry)

NameError: name 'sham_arry' is not defined

In [212]:
import numpy as nm

In [214]:
simple_list=[6,7,9]
nm.array(simple_list)

array([6, 7, 9])

In [272]:
list_of_array=[1,2,3],[4,5,6]
nm.array(list_of_array)

array([[1, 2, 3],
       [4, 5, 6]])

In [271]:
nm.array(1,49)

TypeError: Cannot interpret '49' as a data type

In [217]:
list=[1,2,3,4,5,6]

In [218]:
len(list)

6

In [229]:
list[3:4]

[4]

In [247]:
fruit=["Apple","Orange","Guawa","Tea"]
fruit.append("Mango")
print(fruit)

['Apple', 'Orange', 'Guawa', 'Tea', 'Mango']


In [248]:
fruit.pop(3)
print(fruit)

['Apple', 'Orange', 'Guawa', 'Mango']


In [249]:
fruit.insert(3,"Banana")
print(fruit)

['Apple', 'Orange', 'Guawa', 'Banana', 'Mango']


In [250]:
len(fruit)

5

In [251]:
fruit.index("Mango")

4

In [257]:
fruit.sort()
print(fruit)

['Apple', 'Banana', 'Guawa']


In [258]:
fruit.pop(-1)
print(fruit)

['Apple', 'Banana']


In [259]:
simple_list[1] = 10 
simple_list

[6, 10, 9]

In [260]:
simple_list.reverse()
simple_list

[9, 10, 6]

### hjhguiteyi

# hggfgugk

### fjurtfhg

In [62]:
students_name(1) ="nainu"
students_name

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (879104949.py, line 1)

In [9]:
Students_name = ('naina','karuna','shanu''suman')
Students_name

('naina', 'karuna', 'shanusuman')

In [10]:
x = 1+2j
type(x)

complex

In [13]:
sample_list[2
        ]

'hi'

In [18]:
sample_list = [ 12,4.3,"hi",23]
sample_list

[12, 4.3, 'hi', 23]

In [26]:
sample_list[2]

'hellow'

In [27]:
sample_list.pop(3)

23

In [33]:
sample_list.append("ring")
sample_list

[12, 4.3, 'hellow', 5, 'ring', 'ring', 'ring']

In [35]:
sample_list.append(5)
sample_list

[12, 4.3, 'hellow', 5, 'ring', 'ring', 'ring', 5, 5]

simple_list =[12,4.3,"Hi",1-2j]
simple_list

In [38]:
simple_list =[13,4.4,"Hello",1-3j]
simple_list

[13, 4.4, 'Hello', (1-3j)]

In [49]:
simple_list[2]="Hell"
simple_list

[13, 4.4, 'Hell', 23]

In [50]:
simple_list[3]=23
simple_list

[13, 4.4, 'Hell', 23]

In [51]:
studentname=["apple","mango","graps","orange","karuna","sumit","shanu"]
studentname


['apple', 'mango', 'graps', 'orange', 'karuna', 'sumit', 'shanu']

In [52]:
studentname[6]="suman"
studentname

['apple', 'mango', 'graps', 'orange', 'karuna', 'sumit', 'suman']

In [55]:
studentname.pop(1)
studentname

['apple', 'graps', 'orange', 'karuna', 'sumit', 'suman']

In [57]:
list =['p','y','t','h','o','n']
list

['p', 'y', 't', 'h', 'o', 'n']

sample_list[2] = "hellow"

In [275]:
list[-5:-3]

[2, 3]

In [ ]:
import numpy as np

In [276]:
list =['p','y','t','h','o','n']
list

['p', 'y', 't', 'h', 'o', 'n']

In [278]:
list[-5:-3]

['y', 't']

In [16]:
sample_list[2] = "hellow"

In [191]:
sample_list =[12,4.3,"hi",23]
sample_list

[12, 4.3, 'hi', 23]

In [201]:
sample_list.pop()
sample_list

[12, 4.3, 'hi']

In [200]:
print("Hello World")

Hello World


In [299]:
arr =np.array('i',[1,2,3])
arr

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [ ]:
import numpy as np

In [300]:
list =([1,2,3],[4,5,6],[7,8,9])
np.array(list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [301]:
np.arange(15,27,3)

array([15, 18, 21, 24])

In [303]:
np.arange(27,15,3)

array([], dtype=int32)

In [304]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [305]:
np.ones(4)

array([1., 1., 1., 1.])

In [315]:
np.sample_array =([1,2,3,4,5,6,7,8,9])
np.sample_array

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [316]:
sample_array=np.reshape(2,3)
sample_array

ValueError: cannot reshape array of size 1 into shape (3,)